---
# Ansible playbook to Uninstall and Install NMX

- name: Auto Uninstall and Install NMX
  hosts: all
  gather_facts: false
  tasks:
  - name: Get active catalog name
    win_reg_stat:
      path: HKLM:\SOFTWARE\Harmonic\MEM
      name: ServiceSQLServerDSN
      register: ActiveCatalog
  - name: Create NMXInstall.ini file
    win_copy:
      dest: C:\NMXInstall.ini
      content: |
        [Option]
        SiteID="{{SiteID}}"
        SQLServerName=localhost
        Catalog=ActiveCatalog.value
        SQLServerBackupDir=C:\databasebkup
  - name: Create NMXUninstall.ini file
    win_copy:
      dest: C:\NMXUninstall.ini
      content: |
        ! QuickInstall, 0 - Proceed with uninstallation, 1 - Skip uninstallation.
        ! 1 Silent Mode True, Any other value  - False.
        [Mode]
        Silent=1
        Catalog=ActiveCatalog.value
        QuickInstall=1
  - name: check if NMX is already installed
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{0940EFBB-D1FC-4C6F-91E0-996D9E40B2A2}_is1
      register: NMX_Installed
  - name: Uninstall NMX
    win_package:
        path: C:\Program Files\Harmonic\unins001.exe
        product_id: '{0940EFBB-D1FC-4C6F-91E0-996D9E40B2A2}_is1'
        arguments: /SP- /SILENT /SUPPRESSMSGBOXES
        reboot_required: true
        state: absent
        when: NMX_Installed.exists == true
  - name: Install NMX
    win_package:
      path: C:\Temp\nmx\8.0.0.0.37-A\Install_NMX_8.0.0.0.37-A.exe
      product_id: '{0940EFBB-D1FC-4C6F-91E0-996D9E40B2A2}_is1'
      arguments: /SP- /SILENT /SUPPRESSMSGBOXES /Type=ClientAndServer /NDDS_DOMAINID="{{SiteID}}"
      reboot_required: true
      state: present
