---
# Ansible playbook to Uninstall and Install NMX

- name: Auto Uninstall and Install NMX
  hosts: all
  gather_facts: false
  tasks:
  - name: check if NMX is already installed
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{0940EFBB-D1FC-4C6F-91E0-996D9E40B2A2}_is1
      register: NMX_Installed
  - name: Uninstall NMX
    win_package:
        path: C:\Program Files\Harmonic\unins001.exe
        product_id: '{0940EFBB-D1FC-4C6F-91E0-996D9E40B2A2}_is1'
        arguments: /SP- /SILENT /SUPPRESSMSGBOXES
        reboot_required: true
        state: absent
        when: NMX_Installed.exists == true
  - name: Install NMX
    win_package:
      path: C:\Temp\nmx\8.0.0.0.37-A\Install_NMX_8.0.0.0.37-A.exe
      product_id: '{0940EFBB-D1FC-4C6F-91E0-996D9E40B2A2}_is1'
      arguments: /SP /SILENT /SUPPRESSMSGBOXES
      reboot_required: true
      state: present
      register: NMX_ReInstalled
  - name: reboot host if required
    win_reboot:
      when: NMX_ReInstalled.reboot_required == true
