---
# Ansible playbook to Uninstall and Install NMX

- name: Auto Uninstall and Install NMX
  hosts: all
  gather_facts: false
  tasks:
  - name: Uninstall NMX
    win_package:
        path: C:\Program Files\Harmonic\unins000.exe
        product_id:{0940EFBB-D1FC-4C6F-91E0-996D9E40B2A2}_is1
        arguments: /SP- /SILENT /SUPPRESSMSGBOXES
        state: absent
