---
# Ansible playbook to Uninstall and Install NMX

- name: Auto Uninstall and Install NMX
  hosts: all
  gather_facts: false
  tasks:
  - name: Uninstall NMX
    win_package:
        path: C:\Program Files\Harmonic\unins000.exe
        product_id: NMX
        arguments: /SP- /SILENT /SUPPRESSMSGBOXES
        state: absent